import { Column, Entity, OneToOne, PrimaryGeneratedColumn } from 'typeorm'

import { User } from '@/user/entity/user.entity'
import { eGenderRole } from '@/_app/constants/enum'

@Entity({ name: 'dbo-customer' })
export class Customer {
  //#region Properties
  /**
   * @description The primary key for the customer entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'uc-id' })
  uid: number

  /**
   * @description The birthday of the customer, which can be used for personalized marketing and promotions
   * This column is nullable, as not all customers may choose to provide their birthday, and it is of type Date to represent the date of birth of the customer
   */
  @Column({ name: 'uc-birthday', type: 'date', nullable: true })
  birthday: Date

  /**
   * @description The gender of the customer, which can be used for demographic analysis and targeted marketing
   * This column is nullable, as not all customers may choose to provide their gender, and it is of type enum to restrict the values to either 'MALE' or 'FEMALE'
   */
  @Column({ name: 'uc-gender', type: 'simple-array', nullable: true })
  gender: eGenderRole

  /**
   * @description The address of the customer, which can be used for shipping and billing purposes
   * This column is nullable, as not all customers may choose to provide their address, and it is of type string to allow for a descriptive address to be provided
   */
  @Column({ name: 'uc-address', nullable: true })
  address: string

  /**
   * @description Indicates whether the customer is a VIP (Very Important Person), which can be used for special treatment and exclusive offers
   *  This column is of type boolean and has a default value of false, meaning that by default, customers are not considered VIPs unless explicitly marked as such
   */
  @Column({ name: 'uc-vip', type: 'boolean' })
  isVip: boolean

  //#region Relations
  /**
   * @description The user associated with the customer, which represents the account information for the customer
   */
  @OneToOne(() => User, (user) => user.customer)
  user: User
  //#endregion
}
