import { Column, Entity, OneToOne, PrimaryGeneratedColumn } from 'typeorm'
import { User } from './user.entity'

@Entity({ name: 'dbo-customer' })
export class Customer {
  //#region Properties
  /**
   * @description The primary key for the customer entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'uc-id' })
  cid: number

  /**
   * @description The phone number of the customer, which can be used for contact purposes
   */
  @Column({ name: 'uc-phone', unique: true })
  phone: string

  /**
   * @description The loyalty points of the customer, which can be used for rewards and discounts
   * This column is nullable, as not all customers may have loyalty points, and it is of type number to represent the points accumulated by the customer
   */
  @Column({ name: 'loyalty-points', type: 'int', nullable: true })
  loyaltyPoints: number

  /**
   * @description The birthday of the customer, which can be used for personalized marketing and promotions
   * This column is nullable, as not all customers may choose to provide their birthday, and it is of type Date to represent the date of birth of the customer
   */
  @Column({ name: 'birthday', type: 'date', nullable: true })
  birthday: Date

  /**
   * @description The gender of the customer, which can be used for demographic analysis and targeted marketing
   * This column is nullable, as not all customers may choose to provide their gender, and it is of type enum to restrict the values to either 'MALE' or 'FEMALE'
   */
  @Column({ name: 'gender', type: 'enum', enum: ['MALE', 'FEMALE'], nullable: true })
  gender: 'MALE' | 'FEMALE'

  /**
   * @description The address of the customer, which can be used for shipping and billing purposes
   * This column is nullable, as not all customers may choose to provide their address, and it is of type string to allow for a descriptive address to be provided
   */
  @Column({ nullable: true })
  address: string

  /**
   * @description Indicates whether the customer is a VIP (Very Important Person), which can be used for special treatment and exclusive offers
   *  This column is of type boolean and has a default value of false, meaning that by default, customers are not considered VIPs unless explicitly marked as such
   */
  @Column({ default: false })
  isVip: boolean

  /**
   * @description Indicates whether the customer is blacklisted, which can be used to restrict access to services or products for customers who have violated policies or caused issues in the past
   * This column is of type boolean and has a default value of false, meaning that by default, customers are not blacklisted unless explicitly marked as such
   */
  @Column({ default: false })
  isBlacklisted: boolean

  /**
   * @description The reason for blacklisting the customer, which can provide context and justification for the blacklisting decision
   * This column is nullable, as not all customers may be blacklisted, and it is of type string to allow for a descriptive reason to be provided when a customer is blacklisted
   */
  @Column({ nullable: true })
  blacklistReason: string

  /**
   * @description The date and time when the customer was blacklisted, which can be used for tracking and auditing purposes
   * This column is nullable, as not all customers may be blacklisted, and it is of type timestamp to represent the exact date and time when the blacklisting occurred
   */
  @Column({ type: 'timestamp', nullable: true })
  blacklistedAt: Date

  //#region Relations
  /**
   * @description The user associated with the customer, which represents the account information for the customer
   */
  @OneToOne(() => User, (user) => user.customer, { cascade: true, onDelete: 'CASCADE' })
  user: User
  //#endregion
}
