import { Column, Entity, OneToOne, PrimaryGeneratedColumn } from 'typeorm'

import { User } from '@/user/entity/user.entity'

@Entity({ name: 'dto-employee' })
export class Employee {
  //#region Properties
  /**
   * @description The primary key for the employee entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'ue-id' })
  uid: number

  /**
   * @description The unique code for the employee, which can be used for identification purposes
   */
  @Column({ name: 'ue-code', unique: true })
  code: string

  /**
   * @description The position of the employee.
   * true if the employee is in a managerial position, false otherwise.
   */
  @Column({ name: 'ue-position' })
  position: boolean

  /**
   * @description The hire date of the employee, which indicates when the employee started working for the company
   */
  @Column({ name: 'ue-hired-at', type: 'datetime', nullable: false, default: () => 'CURRENT_TIMESTAMP' })
  hiredAt: Date

  /**
   * @description The end date of the employee's employment, which indicates when the employee stopped working for the company. It is optional and defaults to the current date if not provided.
   */
  @Column({ name: 'ue-ended-at', type: 'datetime', nullable: true, default: () => 'CURRENT_TIMESTAMP' })
  endedAt: Date

  /**
   * @description The job title of the employee, which indicates the role or position held by the employee within the company. It is optional and can be null if not provided.
   * The job title can be used to provide additional information about the employee's responsibilities and level within the organization.
   */
  @Column({ name: 'ue-job-title', type: 'varchar', length: 255, nullable: true })
  jobTitle: string

  /**
   * @description The status of the employee, which indicates whether the employee is currently active or not. It is a boolean value where true represents an active employee and false represents an inactive employee.
   */
  @Column({ name: 'ue-status' })
  status: boolean

  //#region Relations
  /**
   * @description The user associated with the employee, which represents the account information for the employee
   */
  @OneToOne(() => User, (user) => user.employee)
  user: User
  //#endregion
}
