import { Column, Entity, OneToOne, PrimaryGeneratedColumn } from 'typeorm'

import { User } from '@/user/entity/user.entity'

@Entity({ name: 'dto-employee' })
export class Employee {
  //#region Properties
  /**
   * @description The primary key for the employee entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'ue-id' })
  uid: number

  /**
   * @description The unique code for the employee, which can be used for identification purposes
   */
  @Column({ name: 'ue-code', unique: true })
  code: string

  /**
   * @description The position of the employee.
   * true if the employee is in a managerial position, false otherwise.
   */
  @Column({ name: 'ue-position' })
  position: boolean

  /**
   * @description The phone number of the employee, which can be used for contact purposes
   */
  @Column({ name: 'ue-phone', unique: true })
  phone: string

  /**
   * @description The hire date of the employee, which indicates when the employee started working for the company
   */
  @Column({ name: 'ue-hired-at', type: 'datetime', nullable: false, default: () => 'CURRENT_TIMESTAMP' })
  hiredAt: Date
  //#endregion

  //#region Relations
  /**
   * @description The user associated with the employee, which represents the account information for the employee
   */
  @OneToOne(() => User, (user) => user.employee, { cascade: true, onDelete: 'CASCADE' })
  user: User
  //#endregion
}
