import { Check, Column, CreateDateColumn, DeleteDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn, OneToOne, JoinColumn, BeforeInsert, BeforeUpdate } from 'typeorm'
import { hash } from 'bcrypt'

import { Employee } from '@/user/entity/employee.entity'
import { Customer } from '@/user/entity/customer.entity'
import { eUserAbility, eUserRole } from '@/_app/constants/enum'
import { SALT_ROUND, ROLE_ABILITIES } from '@/_app/constants/const'

@Entity({ name: 'dbo-user' })
export class User {
  //#region Properties
  /**
   * @description The primary key for the user entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'u-id' })
  uid: number

  /**
   * @description The first name of the user
   */
  @Column({ name: 'u-first-name' })
  firstName: string

  /**
   * @description The last name of the user
   */
  @Column({ name: 'u-last-name' })
  lastName: string

  /**
   * @description The email should be unique for each user
   */
  @Column({ name: 'u-email', unique: true })
  email: string

  /**
   * @description The password should be hashed before being stored in the database
   */
  @Column({ name: 'u-password' })
  @Check(`CHAR_LENGTH(u_password) >= 8`)
  password: string

  /**
   * @description The phone number of the user, which can be used for contact purposes
   */
  @Column({ name: 'u-phone', unique: true, nullable: true })
  phone: string

  /**
   * @description The role of the user, which can be one of the values defined in the eUserRole enum
   * This column is stored as an enum in the database, ensuring that only valid roles can be assigned to users
   */
  @Column({ name: 'u-role', type: 'enum', enum: eUserRole, default: 'GUEST' })
  role: eUserRole

  /**
   * @description The abilities of the user, which is a many-to-many relationship with the Ability entity
   */
  @Column({ name: 'u-abilities', type: 'simple-array', nullable: true })
  abilities: eUserAbility[]

  /**
   * @description The googleId column is used to store the unique identifier for users who sign in with Google OAuth
   */
  @Column({ name: 'u-google-id', unique: true, nullable: true })
  googleId: string

  /**
   * @description The avatar column is used to store the URL of the user's avatar image, which can be displayed in the user interface
   */
  @Column({ name: 'u-avatar', nullable: true })
  avatar: string

  /**
   * @description The createdAt column is automatically managed by TypeORM
   */
  @CreateDateColumn({ name: 'u-created-at' })
  createdAt: Date

  /**
   * @description The updatedAt column is automatically managed by TypeORM
   * and is updated whenever the user entity is updated
   */
  @UpdateDateColumn({ name: 'u-updated-at' })
  updatedAt: Date

  /**
   * @description The deletedAt column is automatically managed by TypeORM
   * and is updated whenever the user entity is romoved
   */
  @DeleteDateColumn({ name: 'u-deleted-at' })
  deletedAt: Date

  /**
   * @description The verifiedAt column is used to track when a user's email has been verified
   */
  @Column({ name: 'u-verified-at', type: 'datetime', nullable: true, default: null })
  verfiedAt: Date
  //#endregion

  //#region Relations
  /**
   * @description represents a one-to-one relationship between the User entity and the Employee entity
   * Each user can be associated with one employee, and each employee can be associated with one user
   * The relationship is defined using the @OneToOne decorator, which specifies the target entity (Employee) and the inverse side of the relationship (employee.user)
   */
  @OneToOne(() => Employee, (employee) => employee.user, { cascade: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'ue-employee-uid' })
  employee: Employee

  /**
   * @description represents a one-to-one relationship between the User entity and the Customer entity
   * Each user can be associated with one customer, and each customer can be associated with one user
   * The relationship is defined using the @OneToOne decorator, which specifies the target entity (Customer) and the inverse side of the relationship (customer.user)
   */
  @OneToOne(() => Customer, (customer) => customer.user, { cascade: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'uc-customer-uid' })
  customer: Customer
  //#endregion

  //#region Methods
  /**
   * @description Concatenates the first name and last name to return the full name of the user
   *
   * @returns The full name of the user as a string
   */
  public getFullName = (): string => {
    return `${this.firstName} ${this.lastName}`
  }

  /**
   * @description Hashes the user's password before inserting or updating the user entity in the database
   * This method is decorated with @BeforeInsert and @BeforeUpdate to ensure that the password is always hashed before being stored in the database
   *
   * @returns A promise that resolves when the password has been hashed and updated in the user entity
   */
  @BeforeInsert()
  @BeforeUpdate()
  public hashPassword = async (): Promise<void> => {
    if (this.password) this.password = await hash(this.password, SALT_ROUND)
  }

  /**
   * @description Generates the user's abilities based on their role after the user entity has been inserted into the database
   * This method is decorated with @AfterInsert to ensure that the abilities are generated after the user has been successfully inserted into the database
   * The abilities are assigned based on the user's role, with ADMIN having all abilities, BUSINESS_OWNER having a specific set of abilities, and BUSINESS_STUFF having a more limited set of abilities
   *
   * @returns void
   */
  @BeforeInsert()
  public generateAbilitiesBasedOnRole = (): void => {
    switch (this.role) {
      case eUserRole.ADMIN:
        this.abilities = Object.values(eUserAbility) as eUserAbility[]
        break
      case eUserRole.BUSINESS_OWNER:
        this.abilities = ROLE_ABILITIES[eUserRole.BUSINESS_OWNER] as eUserAbility[]
        break
      case eUserRole.BUSINESS_STUFF:
        this.abilities = ROLE_ABILITIES[eUserRole.BUSINESS_STUFF] as eUserAbility[]
        break
      case eUserRole.CLIENT:
        this.abilities = ROLE_ABILITIES[eUserRole.CLIENT] as eUserAbility[]
        break
      case eUserRole.GUEST:
      default:
        break
    }
  }

  /**
   * @description Adds a new ability to the user's abilities array if it does not already exist
   *
   * @param ability
   * @return true if the ability was added successfully, false if the ability already exists in the user's abilities array
   */
  public addAbility = (ability: eUserAbility): boolean => {
    if (!this.abilities) this.abilities = []
    if (this.abilities.includes(ability)) return false
    this.abilities.push(ability)
    return true
  }

  /**
   * @description Removes an ability from the user's abilities array if it exists
   *
   * @param ability
   * @return true if the ability was removed successfully, false if the ability does not exist in the user's abilities array
   */
  public removeAbility = (ability: eUserAbility): boolean => {
    if (!this.abilities || !this.abilities.includes(ability)) return false
    this.abilities = this.abilities.filter((a) => a !== ability)
    return true
  }
  //#endregion
}
