import { BeforeInsert, BeforeUpdate, Check, Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm'
import { hash } from 'bcrypt'

import { SALT_ROUND } from '@/_app/constants/const'
import { eUserAbility, eUserRole } from '@/_app/constants/enum'

@Entity({ name: 'dbo-users' })
export class User {
  //<editor-fold desc="Properties">
  /**
   * @description The primary key for the user entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'u-id' })
  uid: number

  /**
   * @description The first name of the user
   */
  @Column({ name: 'u-first-name' })
  firstName: string

  /**
   * @description The last name of the user
   */
  @Column({ name: 'u-last-name' })
  lastName: string

  /**
   * @description The email should be unique for each user
   */
  @Column({ name: 'u-email', unique: true })
  email: string

  /**
   * @description The password should be hashed before being stored in the database
   */
  @Column({ name: 'u-password', select: false })
  @Check(`CHAR_LENGTH(u_password) >= 8`)
  password: string

  /**
   * @description The role of the user, which can be one of the values defined in the eUserRole enum
   * This column is stored as an enum in the database, ensuring that only valid roles can be assigned to users
   */
  @Column({ name: 'u-role', type: 'enum', enum: eUserRole, default: 'GUEST' })
  role: eUserRole

  /**
   * @description The abilities of the user, which is a many-to-many relationship with the Ability entity
   */
  @Column({ name: 'u-abilities', type: 'simple-array' })
  abilities: eUserAbility[]

  /**
   * @description The createdAt column is automatically managed by TypeORM
   */
  @CreateDateColumn({ name: 'u-created-at' })
  createdAt: Date

  /**
   * @description The updatedAt column is automatically managed by TypeORM
   * and is updated whenever the user entity is updated
   */
  @UpdateDateColumn({ name: 'u-updated-at' })
  updatedAt: Date
  //</editor-fold>

  //<editor-fold desc="Methods">
  /**
   * @description Concatenates the first name and last name to return the full name of the user
   * @returns The full name of the user as a string
   */
  public getFullName = (): string => {
    return `${this.firstName} ${this.lastName}`
  }

  /**
   * @description Hashes the user's password before inserting or updating the user entity in the database
   * This method is decorated with @BeforeInsert and @BeforeUpdate to ensure that the password is always hashed before being stored in the database
   * @returns A promise that resolves when the password has been hashed and updated in the user entity
   */
  @BeforeInsert()
  @BeforeUpdate()
  public hashPassword = async (): Promise<void> => {
    if (this.password)
      this.password = await hash(this.password, SALT_ROUND)
  }

  /**
   * @description Adds a new ability to the user's abilities array if it does not already exist
   * @param ability
   * @return true if the ability was added successfully, false if the ability already exists in the user's abilities array
   */
  public addAbility = (ability: eUserAbility): boolean => {
    if (!this.abilities) this.abilities = []
    if (this.abilities.includes(ability)) return false
    this.abilities.push(ability)
    return true
  }

  /**
   * @description Removes an ability from the user's abilities array if it exists
   * @param ability
   * @return true if the ability was removed successfully, false if the ability does not exist in the user's abilities array
   */
  public removeAbility = (ability: eUserAbility): boolean => {
    if (!this.abilities.includes(ability)) return false
    this.abilities = this.abilities.filter(a => a !== ability)
    return true
  }
  //</editor-fold>
}