import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm'
import { hash } from 'bcrypt'

@Entity()
export class User {
  //<editor-fold desc="Properties">
  /**
   * @description The primary key for the user entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({name: 'u-id'})
  uid: number
  /**
   * @description The first name of the user
   */
  @Column({name: 'u-first-name'})
  firstName: string
  /**
   * @description The last name of the user
   */
  @Column({name: 'u-last-name'})
  lastName: string
  /**
   * @description The email should be unique for each user
   */
  @Column({name: 'u-email', unique: true})
  email: string
  /**
   * @description The password should be hashed before being stored in the database
   */
  @Column({name: 'u-password'})
  password: string
  //</editor-fold>

  //<editor-fold desc="Methods">
  /**
   * @description Concatenates the first name and last name to return the full name of the user
   * @returns The full name of the user as a string
   */
  public getFullName(): string {
    return `${this.firstName} ${this.lastName}`
  }

  /**
   * @description Hashes the user's password using bcrypt with a salt rounds of 32
   * @returns The hashed password as a string
   */
  public hashPassword(): string {
    return hash(this.password, 32)
  }

  //</editor-fold>
}