import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm'

@Entity({ name: 'dbo-address' })
export class Address {
  //#region Properties
  /**
   * @description The primary key for the address entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'ba-id' })
  uid: number

  /**
   * @description The first line of the address (e.g., street number and name)
   */
  @Column({ name: 'ba-line1' })
  line1: string

  /**
   * @description The second line of the address (e.g., apartment, suite, floor)
   */
  @Column({ name: 'ba-line2', nullable: true })
  line2: string

  /**
   * @description The city of the address
   */
  @Column({ name: 'ba-city' })
  city: string

  /**
   * @description The state or province of the address
   */
  @Column({ name: 'ba-state', nullable: true })
  state: string

  /**
   * @description The postal/zip code of the address
   */
  @Column({ name: 'ba-postal-code' })
  postalCode: string

  /**
   * @description The country of the address (ISO 3166-1 alphba-2 code, e.g., "TN", "US")
   */
  @Column({ name: 'ba-country' })
  country: string

  /**
   * @description The latitude coordinate for geo/map features
   */
  @Column({ name: 'ba-latitude', type: 'decimal', precision: 10, scale: 7, nullable: true })
  latitude: number

  /**
   * @description The longitude coordinate for geo/map features
   */
  @Column({ name: 'ba-longitude', type: 'decimal', precision: 10, scale: 7, nullable: true })
  longitude: number
  //#endregion
}
