import { Column, CreateDateColumn, DeleteDateColumn, Entity, JoinColumn, OneToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm'

import { Address } from '@/business/entity/address.entity'
import { Contact } from '@/business/entity/contact.entity'

@Entity({ name: 'dbo-business' })
export class Business {
  //#region Properties
  /**
   * @description The primary key for the business entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'b-id' })
  uid: number

  /**
   * @description The slug of the business, which should be unique and is used for URL-friendly identifiers
   */
  @Column({ name: 'b-slug', unique: true, nullable: false })
  slug: string

  /**
   * @description The name of the business
   */
  @Column({ name: 'b-name' })
  name: string

  /**
   * @description The slogan of the business, which is a short and catchy phrase that represents the business's brand or mission
   */
  @Column({ name: 'b-slogan' })
  slogan: string

  /**
   * @description The description of the business, which provides more detailed information about the business, its products, services, or values
   */
  @Column({ name: 'b-description', type: 'text' })
  description: string

  /**
   * @description The tax identification number of the business, which should be unique
   */
  @Column({ name: 'b-tax-identification-number', unique: true, nullable: false })
  taxIdentificationNumber: string

  /**
   * @description A boolean flag indicating whether the business can have a loyalty program.
   * This is used to determine if the business is eligible to offer loyalty rewards to its customers.
   */
  @Column({ name: 'b-can-have-loyalty-program' })
  canHaveLoyaltyProgram: boolean = false

  /**
   * @description The createdAt column is automatically managed by TypeORM
   */
  @CreateDateColumn({ name: 'b-created-at' })
  createdAt: Date

  /**
   * @description The updatedAt column is automatically managed by TypeORM
   * and is updated whenever the user entity is updated
   */
  @UpdateDateColumn({ name: 'b-updated-at' })
  updatedAt: Date

  /**
   * @description The deletedAt column is automatically managed by TypeORM
   * and is updated whenever the user entity is romoved
   */
  @DeleteDateColumn({ name: 'b-deleted-at' })
  deletedAt: Date
  //#endregion

  //#region Relations
  /**
   * @description The address associated with the business, which represents the location information for the business.
   * It is a one-to-one relationship, and when a business is deleted, the associated address will also be deleted (cascade delete).
   */
  @OneToOne(() => Address, { cascade: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'ba-address-uid' })
  address: Address

  /**
   * @description The contact information associated with the business, which includes details such as email, phone numbers, and website.
   * It is a one-to-one relationship, and when a business is deleted, the associated contact information will also be deleted (cascade delete).
   */
  @OneToOne(() => Contact, { cascade: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'bc-contact-uid' })
  contact: Contact
  //#endregion
}
