import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm'

@Entity({ name: 'dbo-contact' })
export class Contact {
  //#region Properties
  /**
   * @description The primary key for the user entity, auto-generated by the database
   */
  @PrimaryGeneratedColumn({ name: 'u-id' })
  uid: number

  /**
   * @description The email of the contact, which should be unique for each contact
   */
  @Column({ name: 'bc-email', unique: true })
  email: string

  /**
   * @description The phone numbers of the contact, stored as an array of strings
   * This allows for multiple phone numbers to be associated with a single contact
   */
  @Column({ name: 'bc-phone', type: 'simple-array', nullable: true })
  phone: string[]

  /**
   * @description The website URL of the contact, which is optional and can be null
   */
  @Column({ name: 'bc-website', nullable: true })
  website: string

  /**
   * @description The WhatsApp link of the contact, which is optional and can be null
   */
  @Column({ name: 'bc-whatsapp-link', nullable: true })
  whatappLink: string
  //#endregion
}
