export enum eUserRole {
    ADMIN = 'ADMIN',
    BUSINESS_OWNER = 'BUSINESS_OWNER',
    BUSINESS_STUFF = 'BUSINESS_STUFF',
    CLIENT = 'CLIENT',
    GUEST = 'GUEST'
}

export enum eUserAbility {
    TENANT_MOD = 'TENANT_MOD',
    TENANT_VIEW = 'TENANT_VIEW',
    SUBSCRIPTION_MOD = 'SUBSCRIPTION_MOD',
    SUBSCRIPTION_VIEW = 'SUBSCRIPTION_VIEW',
    BUSINESS_MOD = 'BUSINESS_MOD',
    BUSINESS_VIEW = 'BUSINESS_VIEW',
    EMPLOYEE_MOD = 'EMPLOYEE_MOD',
    EMPLOYEE_VIEW = 'EMPLOYEE_VIEW',
    RESOURCE_MOD = 'RESOURCE_MOD',
    RESOURCE_VIEW = 'RESOURCE_VIEW',
    CLIENT_MOD = 'CLIENT_MOD',
    CLIENT_VIEW = 'CLIENT_VIEW',
    RESERVATION_MOD = 'RESERVATION_MOD',
    RESERVATION_VIEW = 'RESERVATION_VIEW',
    BOOKING_MOD = 'BOOKING_MOD',
    BOOKING_VIEW = 'BOOKING_VIEW',
    BOOKING_CANCEL = 'BOOKING_CANCEL'
}